#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Sep 10, 2025 09:07:01 PM CST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m47 -relief groove -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 721x605+624+200
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "WaveDoc"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    menu "$top.m47" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    text "$top.tex47" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 184 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 229 \
        -wrap word 
    $top.tex47 configure -font "TkTextFont"
    $top.tex47 insert end text
    vTcl:DefineAlias "$top.tex47" "rawMsg" vTcl:WidgetProc "Toplevel1" 1
    bind $top.tex47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {訊息貼這R先生 整個訊息 連名字那些一起}
    }
    label "$top.lab47" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -borderwidth 4 -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify right \
        -relief groove -text " 浪單訊息" 
    vTcl:DefineAlias "$top.lab47" "WaveRawMsgLabel" vTcl:WidgetProc "Toplevel1" 1
    bind $top.lab47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {(點這來生成測試文本)}
    }
    vTcl:copy_lock $top.lab47
    labelframe "$top.lab52" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 -text "訊息生成" \
        -background #d9d9d9 -height 356 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -width 619 
    vTcl:DefineAlias "$top.lab52" "WaveMsg" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab52
    label "$site_3_0.lab56" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief ridge \
        -text "結單訊息" 
    vTcl:DefineAlias "$site_3_0.lab56" "Label3_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab56
    labelframe "$site_3_0.lab73" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 -relief sunken \
        -text "Ew📉" -background #d9d9d9 -height 50 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 279 
    vTcl:DefineAlias "$site_3_0.lab73" "EwEnch" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab73
    button "$site_4_0.but86" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.VFX1Button)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "音效燈" 
    vTcl:DefineAlias "$site_4_0.but86" "VFX1Button" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but86 <<SetBalloon>> {
        set ::vTcl::balloon::%W {The voice of 紲(ㄒㄧㄝˋ)星燈 in a book!}
    }
    vTcl:copy_lock $site_4_0.but86
    button "$site_4_0.but108" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.VFX4Button)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "音效葵" 
    vTcl:DefineAlias "$site_4_0.but108" "VFX4Button" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but108 <<SetBalloon>> {
        set ::vTcl::balloon::%W {The voice of 琴葉葵 in a book!}
    }
    vTcl:copy_lock $site_4_0.but108
    button "$site_4_0.but87" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.VFX2Button)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "音效緣" 
    vTcl:DefineAlias "$site_4_0.but87" "VFX2Button" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but87 <<SetBalloon>> {
        set ::vTcl::balloon::%W {The voice of 結月緣 in a book!}
    }
    vTcl:copy_lock $site_4_0.but87
    button "$site_4_0.but89" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.VFX3Button)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "音效茜(ㄑㄧㄢˋ)" 
    vTcl:DefineAlias "$site_4_0.but89" "VFX3Button" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but89 <<SetBalloon>> {
        set ::vTcl::balloon::%W {The voice of 琴葉茜(ㄑㄧㄢˋ) in a book!}
    }
    vTcl:copy_lock $site_4_0.but89
    place $site_4_0.but86 \
        -in $site_4_0 -x 0 -relx 0.036 -y 0 -rely 0.34 -width 47 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but108 \
        -in $site_4_0 -x 0 -relx 0.771 -y 0 -rely 0.34 -width 47 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but87 \
        -in $site_4_0 -x 0 -relx 0.233 -y 0 -rely 0.34 -width 47 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but89 \
        -in $site_4_0 -x 0 -relx 0.43 -y 0 -rely 0.34 -width 87 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab73
    labelframe "$site_3_0.lab92" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 -relief sunken \
        -text "Bruh😩" -background #d9d9d9 -height 50 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 280 
    vTcl:DefineAlias "$site_3_0.lab92" "BruhEnch" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab92
    button "$site_4_0.but87" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.FloatieButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "浮力" 
    vTcl:DefineAlias "$site_4_0.but87" "FloatieButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but87 <<SetBalloon>> {
        set ::vTcl::balloon::%W {You can make the tooltip of this red and I won't say a word against it}
    }
    vTcl:copy_lock $site_4_0.but87
    button "$site_4_0.but86" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.FastWindButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "疾風" 
    vTcl:DefineAlias "$site_4_0.but86" "FastWindButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but86 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Actually somewhat useful but the supply vastly outpace the demand}
    }
    vTcl:copy_lock $site_4_0.but86
    button "$site_4_0.but90" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.NimbleButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "靈巧" 
    vTcl:DefineAlias "$site_4_0.but90" "NimbleButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but90 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Actually somewhat useful but the supply vastly outpace the demand as well}
    }
    vTcl:copy_lock $site_4_0.but90
    button "$site_4_0.but93" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.OreSmeltButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "礦石熔煉" 
    vTcl:DefineAlias "$site_4_0.but93" "OreSmeltButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but93 <<SetBalloon>> {
        set ::vTcl::balloon::%W {??? WHO EVEN WANTS THIS}
    }
    vTcl:copy_lock $site_4_0.but93
    button "$site_4_0.but89" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.WindHitButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "風擊" 
    vTcl:DefineAlias "$site_4_0.but89" "WindHitButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but89 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Pretty fun enchantment not gonna lie, \nbut fun ≠ useful}
    }
    vTcl:copy_lock $site_4_0.but89
    place $site_4_0.but87 \
        -in $site_4_0 -x 0 -relx 0.215 -y 0 -rely 0.333 -width 40 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but86 \
        -in $site_4_0 -x 0 -relx 0.036 -y 0 -rely 0.333 -width 40 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but90 \
        -in $site_4_0 -x 0 -relx 0.393 -y 0 -rely 0.34 -width 40 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but93 \
        -in $site_4_0 -x 0 -relx 0.571 -y 0 -rely 0.34 -width 60 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but89 \
        -in $site_4_0 -x 0 -relx 0.821 -y 0 -rely 0.34 -width 40 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab92
    text "$site_3_0.tex116" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 19 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 64 \
        -wrap word 
    $site_3_0.tex116 configure -font "TkTextFont"
    $site_3_0.tex116 insert end text
    vTcl:DefineAlias "$site_3_0.tex116" "WaveCount" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tex116 <<SetBalloon>> {
        set ::vTcl::balloon::%W {The wave your doing}
    }
    vTcl:copy_lock $site_3_0.tex116
    label "$site_3_0.lab115" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "進行中場次" 
    vTcl:DefineAlias "$site_3_0.lab115" "Label3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab115
    button "$site_3_0.but64" \
        -activebackground #d9d9d9 -activeforeground black -background #cccccc \
        -command "WaveEndMsgCopy" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "複製訊息" 
    vTcl:DefineAlias "$site_3_0.but64" "WaveEndMsgCopyButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but64 <<SetBalloon>> {
        set ::vTcl::balloon::%W {把浪單資訊以旁邊的格式複製到剪貼簿上}
    }
    vTcl:copy_lock $site_3_0.but64
    button "$site_3_0.but66" \
        -activebackground #d9d9d9 -activeforeground black -background #cccccc \
        -command "WaveVideoTitleCopy" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "複製訊息" 
    vTcl:DefineAlias "$site_3_0.but66" "WaveVideoTitleCopyButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but66 <<SetBalloon>> {
        set ::vTcl::balloon::%W {把浪單資訊以旁邊的格式複製到剪貼簿上}
    }
    vTcl:copy_lock $site_3_0.but66
    button "$site_3_0.but65" \
        -activebackground #d9d9d9 -activeforeground black -background #cccccc \
        -command "WaveStartMsgCopy" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "複製訊息" 
    vTcl:DefineAlias "$site_3_0.but65" "WaveStartMsgCopyButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but65 <<SetBalloon>> {
        set ::vTcl::balloon::%W {把浪單資訊以旁邊的格式複製到剪貼簿上}
    }
    vTcl:copy_lock $site_3_0.but65
    text "$site_3_0.tex67" \
        -background white -borderwidth 3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -height 163 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 311 \
        -wrap word 
    $site_3_0.tex67 configure -font "TkTextFont"
    $site_3_0.tex67 insert end text
    vTcl:DefineAlias "$site_3_0.tex67" "WaveRequestFinishMsgTextElement" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tex67 <<SetBalloon>> {
        set ::vTcl::balloon::%W {你的結單訊息長這樣💥}
    }
    vTcl:copy_lock $site_3_0.tex67
    button "$site_3_0.but121" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "WaveCounterReset" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "重製場次" 
    vTcl:DefineAlias "$site_3_0.but121" "WaveCounterResetButton_1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but121 <<SetBalloon>> {
        set ::vTcl::balloon::%W {進行中場次=1}
    }
    vTcl:copy_lock $site_3_0.but121
    button "$site_3_0.but117" \
        -activebackground #d9d9d9 -activeforeground black -background #cfcfcf \
        -command "WaveCounterPlus" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "下一場" 
    vTcl:DefineAlias "$site_3_0.but117" "WaveCounterPlusButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but117 <<SetBalloon>> {
        set ::vTcl::balloon::%W {進行中場次+=1}
    }
    vTcl:copy_lock $site_3_0.but117
    button "$site_3_0.but119" \
        -activebackground #d9d9d9 -activeforeground black -background #cfcfcf \
        -command "WaveCounterMinus" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "上一場" 
    vTcl:DefineAlias "$site_3_0.but119" "WaveCounterMinusButton_1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but119 <<SetBalloon>> {
        set ::vTcl::balloon::%W {進行中場次-=1}
    }
    vTcl:copy_lock $site_3_0.but119
    button "$site_3_0.but125" \
        -activebackground #d9d9d9 -activeforeground black -background #cfcfcf \
        -command "RemoveEnch" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "刪除附魔" 
    vTcl:DefineAlias "$site_3_0.but125" "RemoveEnchButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but125 <<SetBalloon>> {
        set ::vTcl::balloon::%W {刪除那行最後面的附魔}
    }
    vTcl:copy_lock $site_3_0.but125
    button "$site_3_0.but123" \
        -activebackground #d9d9d9 -activeforeground black -background #cfcfcf \
        -command "ResetWaveRequestFinishMsg" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "重製訊息" 
    vTcl:DefineAlias "$site_3_0.but123" "WaveRequestFinishMsgButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but123 <<SetBalloon>> {
        set ::vTcl::balloon::%W {重製整個結單訊息}
    }
    vTcl:copy_lock $site_3_0.but123
    button "$site_3_0.but124" \
        -activebackground #d9d9d9 -activeforeground black -background #cccccc \
        -command "WaveRequestFinishMsgCopy" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "複製訊息" 
    vTcl:DefineAlias "$site_3_0.but124" "WaveRequestFinishMsgCopyButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but124 <<SetBalloon>> {
        set ::vTcl::balloon::%W {把結單訊息複製到你的剪貼簿裡}
    }
    vTcl:copy_lock $site_3_0.but124
    label "$site_3_0.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief ridge \
        -text "浪潮起始訊息格式" 
    vTcl:DefineAlias "$site_3_0.lab53" "Label3_1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.lab53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {%C = 當前波數, %Dif = 浪潮難度, %Mode = 訂單模式, %B = 買家ID
%Mon = 月份, %D = 日期, %H = 小時, %Min = 分鐘
%MonNow = 月份, %DNow = 日期, %HNow = 小時, %MinNow = 分鐘
文字太長可以使用滾輪查看其他行
換行符號會被當空格, 把欄位清空來回復預設值
(欄位只有在你取消聚焦時會被儲存到設定/回復預設)}
    }
    vTcl:copy_lock $site_3_0.lab53
    text "$site_3_0.tex58" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -height 22 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 213 \
        -wrap word 
    $site_3_0.tex58 configure -font "TkTextFont"
    $site_3_0.tex58 insert end text
    vTcl:DefineAlias "$site_3_0.tex58" "WaveStartMsgFormat" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tex58 <<SetBalloon>> {
        set ::vTcl::balloon::%W {%C = 當前波數, %Dif = 浪潮難度, %Mode = 訂單模式, %B = 買家ID
%Mon = 月份, %D = 日期, %H = 小時, %Min = 分鐘
%MonNow = 月份, %DNow = 日期, %HNow = 小時, %MinNow = 分鐘
文字太長可以使用滾輪查看其他行
換行符號會被當空格, 把欄位清空來回復預設值
(欄位只有在你取消聚焦時會被儲存到設定/回復預設)}
    }
    vTcl:copy_lock $site_3_0.tex58
    label "$site_3_0.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief ridge \
        -text "浪潮結束訊息格式" 
    vTcl:DefineAlias "$site_3_0.lab55" "Label3_1_1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.lab55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {%C = 當前波數, %Dif = 浪潮難度, %Mode = 訂單模式, %B = 買家ID
%Mon = 月份, %D = 日期, %H = 小時, %Min = 分鐘
%MonNow = 月份, %DNow = 日期, %HNow = 小時, %MinNow = 分鐘
文字太長可以使用滾輪查看其他行
換行符號會被當空格, 把欄位清空來回復預設值
(欄位只有在你取消聚焦時會被儲存到設定/回復預設)}
    }
    vTcl:copy_lock $site_3_0.lab55
    text "$site_3_0.tex59" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 213 \
        -wrap word 
    $site_3_0.tex59 configure -font "TkTextFont"
    $site_3_0.tex59 insert end text
    vTcl:DefineAlias "$site_3_0.tex59" "WaveEndMsgFormat" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tex59 <<SetBalloon>> {
        set ::vTcl::balloon::%W {%C = 當前波數, %Dif = 浪潮難度, %Mode = 訂單模式, %B = 買家ID
%Mon = 月份, %D = 日期, %H = 小時, %Min = 分鐘
%MonNow = 月份, %DNow = 日期, %HNow = 小時, %MinNow = 分鐘
文字太長可以使用滾輪查看其他行
換行符號會被當空格, 把欄位清空來回復預設值
(欄位只有在你取消聚焦時會被儲存到設定/回復預設)}
    }
    vTcl:copy_lock $site_3_0.tex59
    label "$site_3_0.lab57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief ridge \
        -text "浪潮影片標題格式" 
    vTcl:DefineAlias "$site_3_0.lab57" "Label3_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.lab57 <<SetBalloon>> {
        set ::vTcl::balloon::%W {%C = 當前波數, %Dif = 浪潮難度, %Mode = 訂單模式, %B = 買家ID
%Mon = 月份, %D = 日期, %H = 小時, %Min = 分鐘
%MonNow = 月份, %DNow = 日期, %HNow = 小時, %MinNow = 分鐘
文字太長可以使用滾輪查看其他行
換行符號會被當空格, 把欄位清空來回復預設值
(欄位只有在你取消聚焦時會被儲存到設定/回復預設)}
    }
    vTcl:copy_lock $site_3_0.lab57
    text "$site_3_0.tex63" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 213 \
        -wrap word 
    $site_3_0.tex63 configure -font "TkTextFont"
    $site_3_0.tex63 insert end text
    vTcl:DefineAlias "$site_3_0.tex63" "WaveVideoTitleFormat" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tex63 <<SetBalloon>> {
        set ::vTcl::balloon::%W {%C = 當前波數, %Dif = 浪潮難度, %Mode = 訂單模式, %B = 買家ID
%Mon = 月份, %D = 日期, %H = 小時, %Min = 分鐘
%MonNow = 月份, %DNow = 日期, %HNow = 小時, %MinNow = 分鐘
文字太長可以使用滾輪查看其他行
換行符號會被當空格, 把欄位清空來回復預設值
(欄位只有在你取消聚焦時會被儲存到設定/回復預設)}
    }
    vTcl:copy_lock $site_3_0.tex63
    labelframe "$site_3_0.lab95" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 -relief sunken \
        -text "Meh👨" -background #d9d9d9 -height 110 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 281 
    vTcl:DefineAlias "$site_3_0.lab95" "MehEnch" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab95
    button "$site_4_0.but90" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.SmartButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "智慧" 
    vTcl:DefineAlias "$site_4_0.but90" "SmartButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but90 <<SetBalloon>> {
        set ::vTcl::balloon::%W {I think 60$ is under valued, but it would be so expensive to get a Smart V otherwise}
    }
    vTcl:copy_lock $site_4_0.but90
    button "$site_4_0.but96" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.FrozenButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "冰凍" 
    vTcl:DefineAlias "$site_4_0.but96" "FrozenButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but96 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Does this enchantment really matter?}
    }
    vTcl:copy_lock $site_4_0.but96
    button "$site_4_0.but97" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.SpearButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "長矛" 
    vTcl:DefineAlias "$site_4_0.but97" "SpearButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but97 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Now I can also have Reach!}
    }
    vTcl:copy_lock $site_4_0.but97
    button "$site_4_0.but93" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.CritButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "爆擊可能" 
    vTcl:DefineAlias "$site_4_0.but93" "CritButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but93 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Even my damage is depend on RNG now bruhhhh}
    }
    vTcl:copy_lock $site_4_0.but93
    button "$site_4_0.but105" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.YummyButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "美食" 
    vTcl:DefineAlias "$site_4_0.but105" "YummyButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but105 <<SetBalloon>> {
        set ::vTcl::balloon::%W {This makes garrot a lot more 
convenient to use}
    }
    vTcl:copy_lock $site_4_0.but105
    button "$site_4_0.but87" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.HealthyButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "健康" 
    vTcl:DefineAlias "$site_4_0.but87" "HealthyButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but87 <<SetBalloon>> {
        set ::vTcl::balloon::%W {I wish this have V}
    }
    vTcl:copy_lock $site_4_0.but87
    button "$site_4_0.but89" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.StubbronButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "倔強" 
    vTcl:DefineAlias "$site_4_0.but89" "StubbronButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but89 <<SetBalloon>> {
        set ::vTcl::balloon::%W {God damn it we are always low on this one}
    }
    vTcl:copy_lock $site_4_0.but89
    button "$site_4_0.but52" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.MiniButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "迷你化" 
    vTcl:DefineAlias "$site_4_0.but52" "MiniButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but52 <<SetBalloon>> {
        set ::vTcl::balloon::%W {400$? That is definitely overpriced}
    }
    button "$site_4_0.but102" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.KBresButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "擊退保護" 
    vTcl:DefineAlias "$site_4_0.but102" "KBresButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but102 <<SetBalloon>> {
        set ::vTcl::balloon::%W {The backbone of the SOB meta}
    }
    vTcl:copy_lock $site_4_0.but102
    button "$site_4_0.but99" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.ExpSacButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "獻祭經驗" 
    vTcl:DefineAlias "$site_4_0.but99" "ExpSacButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but99 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Free damage resistence! (until u die)}
    }
    vTcl:copy_lock $site_4_0.but99
    button "$site_4_0.but101" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.SteadySneakButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "穩重潛行" 
    vTcl:DefineAlias "$site_4_0.but101" "SteadySneakButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but101 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Kinda hate this enchantment sometimes}
    }
    vTcl:copy_lock $site_4_0.but101
    button "$site_4_0.but104" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.AntiBreakButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "損毀救援" 
    vTcl:DefineAlias "$site_4_0.but104" "AntiBreakButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but104 <<SetBalloon>> {
        set ::vTcl::balloon::%W {I think this is actually useful, saves me a lot when Im not being careful}
    }
    vTcl:copy_lock $site_4_0.but104
    button "$site_4_0.but86" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.BloodSuckingButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "吸血" 
    vTcl:DefineAlias "$site_4_0.but86" "BloodSuckingButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but86 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Like other said, everyone think this book sucked until they used it}
    }
    vTcl:copy_lock $site_4_0.but86
    button "$site_4_0.but98" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.ExtendButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "延伸" 
    vTcl:DefineAlias "$site_4_0.but98" "ExtendButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but98 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Not sure if this is actually useful outside of bed mining, \nwould be a god enchantment if combind with magnet touch tho :pepepray:}
    }
    vTcl:copy_lock $site_4_0.but98
    button "$site_4_0.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.UnGoneAbleButton)" \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "不滅" 
    vTcl:DefineAlias "$site_4_0.but50" "UnGoneAbleButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {If only this enchantment can be put on more things...}
    }
    place $site_4_0.but90 \
        -in $site_4_0 -x 0 -relx 0.197 -y 0 -rely 0.182 -width 40 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but96 \
        -in $site_4_0 -x 0 -relx 0.358 -y 0 -rely 0.182 -width 40 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but97 \
        -in $site_4_0 -x 0 -relx 0.52 -y 0 -rely 0.182 -width 40 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but93 \
        -in $site_4_0 -x 0 -relx 0.036 -y 0 -rely 0.455 -width 60 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but105 \
        -in $site_4_0 -x 0 -relx 0.269 -y 0 -rely 0.455 -width 40 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but87 \
        -in $site_4_0 -x 0 -relx 0.43 -y 0 -rely 0.455 -width 40 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but89 \
        -in $site_4_0 -x 0 -relx 0.591 -y 0 -rely 0.455 -width 40 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but52 \
        -in $site_4_0 -x 0 -relx 0.75 -y 0 -rely 0.455 -width 55 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but102 \
        -in $site_4_0 -x 0 -relx 0.036 -y 0 -rely 0.727 -width 60 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but99 \
        -in $site_4_0 -x 0 -relx 0.267 -y 0 -rely 0.727 -width 60 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but101 \
        -in $site_4_0 -x 0 -relx 0.502 -y 0 -rely 0.727 -width 60 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but104 \
        -in $site_4_0 -x 0 -relx 0.735 -y 0 -rely 0.727 -width 60 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but86 \
        -in $site_4_0 -x 0 -relx 0.036 -y 0 -rely 0.182 -width 40 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but98 \
        -in $site_4_0 -x 0 -relx 0.681 -y 0 -rely 0.182 -width 40 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but50 \
        -in $site_4_0 -x 0 -relx 0.844 -y 0 -rely 0.182 -width 40 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab95
    labelframe "$site_3_0.lab107" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 -relief sunken \
        -text "Pog🔥" -background #d9d9d9 -height 50 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 280 
    vTcl:DefineAlias "$site_3_0.lab107" "PogEnch" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab107
    button "$site_4_0.but93" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: waveDoc_support.addEnch(self.MendButton)" \
        -cursor draped_box -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "自動修補" 
    vTcl:DefineAlias "$site_4_0.but93" "MendButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but93 <<SetBalloon>> {
        set ::vTcl::balloon::%W {WHY YOU WANT MODDED MENDING ON YOUR SWORD?
IS NOT GOOD ENOUGH AS PROCURED FROM MOJANG STUDIO GAMES?
YOU THINK NEEDS IMPROVEMENT?
THEN MAYBE YOU FIND JOB WITH COMPANY OF SWEDEN! YOU HAVE DRINKS WITH MARKUS ALEXEJ PERSSON,
TRADE STORY OF MANY GAMES DESIGNED AND DETAILS OF SCHOOL FOR WEAPONMAKING!

OR MAYBE YOU NOT DO THIS. PROBABLY IS BECAUSE YOU NEVER MAKE GAME IN WHOLE LIFE.
YOU LOOK AT FINE MINECRAFT ITEMS, THINK IT NEED CRAZY SHIT STICK ON ALL SIDES OF WEAPON.
YOU HAVE DISEASE OF AMERICAN CAPITALIST,
CHANGE THING THAT IS FINE FOR NO REASON EXCEPT TO LOOK DIFFERENT FROM COMRADE.
YOU PUT CHEAP BOOK OF VAMPIRE SLAVE FACTORY ON ONE SIDE, YOU PUT BAD VERSION OF FIRE OF ASPECT ON OTHER SIDE,
YOU PUT THE BRAIN POWER ON BOTTOM SO YOU ARE LIKE AMERICAN SCIENCE GUY NEIL TYSON.
MAYBE YOU PUT SEX DILDO ON TOP TO FUCK YOURSELF IN ASSHOLE FOR MAKING SHAMEFUL TRAVESTY OF WEAPON OF MARKUS ALEXEJ PERSSON, NO?

VANILLA IS FINE.
YOU FUCK IT,
IT ONLY GET EXPENSIVE AND YOU STILL DIE WHEN PING HIGH.
GO TO HYPIXEL SKYWAR, PRACTICE WITH MANY MONTH OF YOUR LIFE.
THEN YOU NOT NEED DUMB SHIT PUT ON SIDE OF WEAPON.}
    }
    place $site_4_0.but93 \
        -in $site_4_0 -x 0 -relx 0.036 -y 0 -rely 0.4 -width 60 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab107
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.016 -y 0 -rely 0.462 -width 0 \
        -relwidth 0.163 -height 0 -relheight 0.045 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 0 -relx 0.533 -y 0 -rely 0.662 -width 0 \
        -relwidth 0.452 -height 0 -relheight 0.141 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab92 \
        -in $site_3_0 -x 0 -relx 0.533 -y 0 -rely 0.521 -width 0 \
        -relwidth 0.452 -height 0 -relheight 0.141 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex116 \
        -in $site_3_0 -x 0 -relx 0.533 -y 0 -rely 0.873 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab115 \
        -in $site_3_0 -x 0 -relx 0.533 -y 0 -rely 0.817 -width 0 \
        -relwidth 0.111 -height 0 -relheight 0.059 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but64 \
        -in $site_3_0 -x 0 -relx 0.403 -y 0 -rely 0.206 -width 57 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but66 \
        -in $site_3_0 -x 0 -relx 0.403 -y 0 -rely 0.318 -width 57 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but65 \
        -in $site_3_0 -x 0 -relx 0.403 -y 0 -rely 0.093 -width 57 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex67 \
        -in $site_3_0 -x 0 -relx 0.016 -y 0 -rely 0.507 -width 0 \
        -relwidth 0.502 -height 0 -relheight 0.459 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but121 \
        -in $site_3_0 -x 0 -relx 0.539 -y 0 -rely 0.938 -width 65 -relwidth 0 \
        -height 16 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but117 \
        -in $site_3_0 -x 0 -relx 0.646 -y 0 -rely 0.901 -width 52 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but119 \
        -in $site_3_0 -x 0 -relx 0.646 -y 0 -rely 0.817 -width 52 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but125 \
        -in $site_3_0 -x 0 -relx 0.735 -y 0 -rely 0.817 -width 57 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but123 \
        -in $site_3_0 -x 0 -relx 0.735 -y 0 -rely 0.901 -width 57 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but124 \
        -in $site_3_0 -x 0 -relx 0.832 -y 0 -rely 0.817 -width 97 -relwidth 0 \
        -height 61 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.016 -y 0 -rely 0.056 -width 0 \
        -relwidth 0.163 -height 0 -relheight 0.045 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex58 \
        -in $site_3_0 -x 0 -relx 0.016 -y 0 -rely 0.099 -width 0 \
        -relwidth 0.382 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.016 -y 0 -rely 0.169 -width 0 \
        -relwidth 0.162 -height 0 -relheight 0.045 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex59 \
        -in $site_3_0 -x 0 -relx 0.016 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.382 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.016 -y 0 -rely 0.282 -width 0 \
        -relwidth 0.162 -height 0 -relheight 0.045 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex63 \
        -in $site_3_0 -x 0 -relx 0.016 -y 0 -rely 0.324 -width 0 \
        -relwidth 0.382 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab95 \
        -in $site_3_0 -x 0 -relx 0.533 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.452 -height 0 -relheight 0.31 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab107 \
        -in $site_3_0 -x 0 -relx 0.533 -y 0 -rely 0.07 -width 0 \
        -relwidth 0.452 -height 0 -relheight 0.141 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.lab52
    labelframe "$top.lab48" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 -text "浪單資訊" \
        -background #d9d9d9 -height 216 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -width 404 
    vTcl:DefineAlias "$top.lab48" "WaveInfo" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab48
    label "$site_3_0.lab59" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "代打次數" 
    vTcl:DefineAlias "$site_3_0.lab59" "Label2_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab59
    label "$site_3_0.lab58" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "訂單模式" 
    vTcl:DefineAlias "$site_3_0.lab58" "Label2_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab58
    label "$site_3_0.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "浪潮模式" 
    vTcl:DefineAlias "$site_3_0.lab54" "Label2_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab54
    label "$site_3_0.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "買家ID" 
    vTcl:DefineAlias "$site_3_0.lab51" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab51
    text "$site_3_0.tex61" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -height 18 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 54 \
        -wrap word 
    $site_3_0.tex61 configure -font "TkTextFont"
    $site_3_0.tex61 insert end text
    vTcl:DefineAlias "$site_3_0.tex61" "RequestTimes" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tex61 <<SetBalloon>> {
        set ::vTcl::balloon::%W {要打幾次都寫在這}
    }
    vTcl:copy_lock $site_3_0.tex61
    checkbutton "$site_3_0.che126" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -command "SetWaveInfoAutoRefresh" -compound left \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -justify left -text "自動更新浪單資訊" \
        -variable "WaveInfoAutoRefresh" 
    vTcl:DefineAlias "$site_3_0.che126" "WaveInfoAutoUpdateToggle" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.che126 <<SetBalloon>> {
        set ::vTcl::balloon::%W {是否在浪單訊息更新時重製結單訊息}
    }
    vTcl:copy_lock $site_3_0.che126
    ttk::combobox "$site_3_0.tCo49" \
        \
        -values "一號 二號 三號 四號 五號 六號 七號 八號 九號 十號 十一號 十二號 十三號 十四號 十五號 十六號 十七號 十八號 十九號 二十號 二十一號 二十二號 二十三號 二十四號 二十五號 二十六號 二十七號 二十八號 二十九號 三十號 三十一號" \
        -font "-family {Segoe UI} -size 9" -textvariable "DateText" 
    vTcl:DefineAlias "$site_3_0.tCo49" "DateSelectionBox" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tCo49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {訂單時間(日期)}
    }
    vTcl:copy_lock $site_3_0.tCo49
    ttk::combobox "$site_3_0.tCo48" \
        -values "一月 二月 三月 四月 五月 六月 七月 八月 九月 十月 十一月 十二月" \
        -font "-family {Segoe UI} -size 9" -textvariable "MonthText" 
    vTcl:DefineAlias "$site_3_0.tCo48" "MonthSelectionBox" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tCo48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {訂單時間(月份)}
    }
    vTcl:copy_lock $site_3_0.tCo48
    ttk::combobox "$site_3_0.tCo51" \
        \
        -values "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59" \
        -font "-family {Segoe UI} -size 9" -textvariable "MinuteText" 
    vTcl:DefineAlias "$site_3_0.tCo51" "MinuteSelectionBox" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tCo51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {訂單時間(分鐘)}
    }
    vTcl:copy_lock $site_3_0.tCo51
    label "$site_3_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "訂單時間" 
    vTcl:DefineAlias "$site_3_0.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab49
    ttk::combobox "$site_3_0.tCo50" \
        \
        -values "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23" \
        -font "-family {Segoe UI} -size 9" -textvariable "HourText" 
    vTcl:DefineAlias "$site_3_0.tCo50" "HourSelectionBox" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tCo50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {訂單時間(小時)}
    }
    vTcl:copy_lock $site_3_0.tCo50
    text "$site_3_0.tex60" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -height 18 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 54 \
        -wrap word 
    $site_3_0.tex60 configure -font "TkTextFont"
    $site_3_0.tex60 insert end text
    vTcl:DefineAlias "$site_3_0.tex60" "RequestMode" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tex60 <<SetBalloon>> {
        set ::vTcl::balloon::%W {(現在還有誰在陪打)}
    }
    vTcl:copy_lock $site_3_0.tex60
    text "$site_3_0.tex56" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -height 18 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 134 \
        -wrap word 
    $site_3_0.tex56 configure -font "TkTextFont"
    $site_3_0.tex56 insert end text
    vTcl:DefineAlias "$site_3_0.tex56" "WaveMode" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tex56 <<SetBalloon>> {
        set ::vTcl::balloon::%W {(大家都訂超困難不是ㄇ)}
    }
    vTcl:copy_lock $site_3_0.tex56
    text "$site_3_0.tex52" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -height 18 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 134 \
        -wrap word 
    $site_3_0.tex52 configure -font "TkTextFont"
    $site_3_0.tex52 insert end text
    vTcl:DefineAlias "$site_3_0.tex52" "BuyerID" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tex52 <<SetBalloon>> {
        set ::vTcl::balloon::%W {誰買的? 看這!}
    }
    vTcl:copy_lock $site_3_0.tex52
    checkbutton "$site_3_0.che134" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -command "SetWaveRequestFinishMsgAutoReset" \
        -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "自動重製結單訊息" -variable "WaveRequestFinishMsgAutoReset" 
    vTcl:DefineAlias "$site_3_0.che134" "WaveRequestFinishMsgAutoResetToggle" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.che134 <<SetBalloon>> {
        set ::vTcl::balloon::%W {是否在浪單訊息有變動時自動更新浪單資訊}
    }
    vTcl:copy_lock $site_3_0.che134
    button "$site_3_0.but136" \
        -activebackground #d9d9d9 -activeforeground black -background #cccccc \
        -command "RefreshWaveInfo" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "更新資訊" 
    vTcl:DefineAlias "$site_3_0.but136" "RefreshWaveInfoButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but136 <<SetBalloon>> {
        set ::vTcl::balloon::%W {手動更新浪單資訊}
    }
    button "$site_3_0.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #cccccc \
        -command "BuyerIDCopy" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "複製ID" 
    vTcl:DefineAlias "$site_3_0.but48" "BuyerIDCopyButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {把浪單資訊以旁邊的格式複製到剪貼簿上}
    }
    button "$site_3_0.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #cccccc \
        -command "BuyerIDCopyFormated" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "複製 /mail new ID" 
    vTcl:DefineAlias "$site_3_0.but47" "BuyerIDCopyFormatedButton" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {把浪單資訊以旁邊的格式複製到剪貼簿上}
    }
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.262 -y 0 -rely 0.683 -width 0 \
        -relwidth 0.159 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.029 -y 0 -rely 0.683 -width 0 \
        -relwidth 0.159 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.029 -y 0 -rely 0.488 -width 0 \
        -relwidth 0.159 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.029 -y 0 -rely 0.293 -width 0 \
        -relwidth 0.159 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex61 \
        -in $site_3_0 -x 0 -relx 0.268 -y 0 -rely 0.78 -width 0 \
        -relwidth 0.159 -height 0 -relheight 0.088 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che126 \
        -in $site_3_0 -x 0 -relx 0.52 -y 0 -rely 0.787 -width 0 \
        -relwidth 0.312 -height 0 -relheight 0.116 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo49 \
        -in $site_3_0 -x 0 -relx 0.322 -y 0 -rely 0.116 -width 0 \
        -relwidth 0.141 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo48 \
        -in $site_3_0 -x 0 -relx 0.173 -y 0 -rely 0.116 -width 0 \
        -relwidth 0.141 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo51 \
        -in $site_3_0 -x 0 -relx 0.619 -y 0 -rely 0.116 -width 0 \
        -relwidth 0.141 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.037 -y 0 -rely 0.116 -width 0 \
        -relwidth 0.134 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo50 \
        -in $site_3_0 -x 0 -relx 0.47 -y 0 -rely 0.116 -width 0 \
        -relwidth 0.141 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex60 \
        -in $site_3_0 -x 0 -relx 0.032 -y 0 -rely 0.78 -width 0 \
        -relwidth 0.159 -height 0 -relheight 0.088 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex56 \
        -in $site_3_0 -x 0 -relx 0.032 -y 0 -rely 0.585 -width 0 \
        -relwidth 0.394 -height 0 -relheight 0.088 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex52 \
        -in $site_3_0 -x 0 -relx 0.032 -y 0 -rely 0.39 -width 0 \
        -relwidth 0.394 -height 0 -relheight 0.088 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che134 \
        -in $site_3_0 -x 0 -relx 0.52 -y 0 -rely 0.694 -width 0 \
        -relwidth 0.312 -height 0 -relheight 0.116 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but136 \
        -in $site_3_0 -x 0 -relx 0.53 -y 0 -rely 0.532 -width 55 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -relx 0.662 -y 0 -rely 0.532 -width 55 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -relx 0.53 -y 0 -rely 0.37 -width 115 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.lab48
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tex47 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.066 -width 0 -relwidth 0.318 \
        -height 0 -relheight 0.304 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.017 -width 0 -relwidth 0.123 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.38 -width 0 -relwidth 0.963 \
        -height 0 -relheight 0.587 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.017 -width 0 -relwidth 0.628 \
        -height 0 -relheight 0.357 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

